version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/  # Nginx 루트 또는 EFS 마운트 경로
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/reload-nginx.sh
      timeout: 300
      runas: root